apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: python-api-deploy-test
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: python-api-deploy-test
    spec:
      containers:
      - name: gke-test
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
