name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file dockerfiles/python-api/Dockerfile --tag williamstjoseph/test-python-api-simple:1.0
    - name: Publish the Docker image 
      run: docker push williamstjoseph/test-python-api-simple:1.0
