name: Docker Image CI

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  path-context:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        dockerfile: ./dockerfiles/python-api/Dockerfile
        repository: williamstjoseph/test-python-api-simple
        tag_with_ref: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
