name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  path-context:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        context: .
        file: ./dockerfile/python-api/Dockerfile
        repository: williamstjoseph/test-python-api-simple
        tag_with_ref: true
